version: '3.4'

services:
  server:
    image: 1podnat
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./development.env

    volumes:
      - .:/opt/1podnat
      - /run/podman/podman.sock:/run/podman/podman.sock
      - /var/lib/containers/storage/volumes:/var/lib/containers/storage/volumes
    ports:
      - 3000:3000
      - 9229:9229
    command: 'npm run start:remotedebug'
  postgres:
    image: postgres:9.6.22-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres:
    external: true
