version: '3.4'

services:
  1podnat:
    image: 1podnat
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./development.env

    volumes:
      - .:/opt/1podnat
      - /run/podman/podman.sock:/run/podman/podman.sock
      - /var/lib/containers/storage/volumes:/var/lib/containers/storage/volumes
    ports:
      - 3000:3000
    command: nest start --watch
